INSERT INTO members (nome, nome_historico, cargo, data_nascimento, ativo) VALUES
('Alceu Batista de Almeida', 'Dom Pedro II', null, null, true),
('Andrey Fernando Servelatti', 'Andrew Carnegie', null, null, true),
('Arvo Marolato Havukainen', 'José Ermírio de Moraes', null, null, false),
('Carlos Augusto Colevatti Lima', 'Carlos Magno', null, null, true),
('Daniel Franco de Oliveira Garcia', 'Andrew Jackson', null, null, true),
('David de Brito Santos', 'Mário Covas', null, null, true),
('Eder Francisco', 'Manuel Deodoro da Fonseca', null, null, true),
('Elnatã Blazutti de Moraes', 'Thomas Jefferson', null, null, true),
('Felipe Tadeu Pereira Andolfato', 'Amadeo Giannini', null, null, false),
('Flávio Vieira', 'Barão de Mauá', null, null, true),
('Giovanni da Silva Almeida Machado', 'Marcus Vitruvius Pollio', null, null, false),
('Henrique de Holanda Polizel', 'Fritz Perls', 'Venerável Mestre', null, true),
('James Alberto Servelatti', 'James Mayer de Rothschild', null, null, true),
('Jazon Olímpio da Silva Junior', 'Benjamin Franklin', null, null, true),
('João Cavinato Sanchez', 'Natan Meyer Rotshchild', null, null, true),
('João Henrique Boliani', 'Adolfo Bezerra de Menezes Cavalcanti', null, null, true),
('José Mendes', 'Castro Alves', null, null, false),
('Luiz Augusto Ferreira Ribeiro', 'Robert Dollar', null, null, false),
('Luiz Claudio Mortais', 'Oscar Niemeyer', null, null, true),
('Marcelo José de Oliveira', 'Duque de Caxias', null, null, true),
('Marcio Henrique Gimenez Cardoso', 'Nikolas Tesla', null, null, true),
('Marco Antônio Natal Vigilato', 'Jigoro Kano', null, null, true),
('Marcus Vinícius Marjoto', 'Jhon Davidson Rockfeller', null, null, true),
('Mario Fernando Madokoro Junior', 'Henry Ford', null, null, true),
('Osvaldo Genari Filho', 'Francisco Cândido Xavier', null, null, true),
('Pablo William Alexandrino Ferraz', 'Alberto Santos Dumont', null, null, true),
('Paulo Mendes Lino', 'Urbano Monte', null, null, true),
('Rafael William da Silva Torresan', 'Assis Chateaubriand', null, null, true),
('Renan Durso Pereira', 'Franklin D. Roosevelt', null, null, true),
('Ricardo do Prado Minarro', 'Abraão', null, null, true),
('Rubens Matheus', 'Ruy Barbosa', null, null, true),
('Silmar José Troleis', 'George Washington', null, null, true),
('Tiago Rodrigues Alves', 'Simon Bolívar', null, null, true),
('Vinicius Locatelli Barbeiro', 'Leonardo di Ser Piero da Vinci', null, null, true),
('Waldiner Rabatski Limieri', 'São Tomas de Aquino', null, null, false),
('Wayner Lora Tozini', 'Jhon Wayne', null, null, true);
